apiVersion: v1
kind: Service
metadata:
  name: {{ include "wirety.fullname" . }}-server
  labels:
    {{- include "wirety.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wirety.server.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wirety.fullname" . }}-frontend
  labels:
    {{- include "wirety.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wirety.frontend.selectorLabels" . | nindent 4 }}
